version: "3.2"
services:
  rabbitmq:
    image: rabbitmq:3-management-alpine
    container_name: "rabbitmq"
    ports:
      - 5672:5672
      - 15672:15672
    environment:
      RABBITMQ_DEFAULT_USER: sqcgo
      RABBITMQ_DEFAULT_PASS: sqcgo
      RABBITMQ_DEFAULT_VHOST: sqcgo
